# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ethan/Documents/github/HWI/Marco_Polo/pyqt_designer/plate_inspector_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlateInspector(object):
    def setupUi(self, PlateInspector):
        PlateInspector.setObjectName("PlateInspector")
        PlateInspector.resize(952, 635)
        self.gridLayout_7 = QtWidgets.QGridLayout(PlateInspector)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_18 = QtWidgets.QLabel(PlateInspector)
        self.label_18.setMaximumSize(QtCore.QSize(200, 30))
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 0, 1, 1)
        self.plateViewer = plateViewer(PlateInspector)
        self.plateViewer.setMinimumSize(QtCore.QSize(200, 0))
        self.plateViewer.setObjectName("plateViewer")
        self.gridLayout_7.addWidget(self.plateViewer, 1, 0, 1, 2)
        self.groupBox_26 = QtWidgets.QGroupBox(PlateInspector)
        self.groupBox_26.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_26.setObjectName("groupBox_26")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_26)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_26)
        self.groupBox_29.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_29.setObjectName("groupBox_29")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_29)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_29)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_12.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_29)
        self.pushButton_21.setEnabled(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_12.addWidget(self.pushButton_21, 1, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_29)
        self.pushButton_22.setEnabled(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_12.addWidget(self.pushButton_22, 2, 0, 1, 2)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_29)
        self.pushButton_20.setEnabled(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_12.addWidget(self.pushButton_20, 1, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_29)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_12.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_29)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_12.addWidget(self.spinBox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_29)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 3, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_29, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_26)
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout.addWidget(self.checkBox_22)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_3.addWidget(self.checkBox_25, 1, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_3.addWidget(self.checkBox_26, 1, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 0, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 0, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_3.addWidget(self.checkBox_6, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_3.setToolTip("")
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_8)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_8)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.tab_8)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_8)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 3, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 4, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 4, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_2.addWidget(self.comboBox_5, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_8)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_5.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_5.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_5.addWidget(self.checkBox_5, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_5.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(150, 30, 67, 17))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_6.addWidget(self.pushButton_23, 1, 5, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_6.addWidget(self.comboBox_7, 1, 2, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_29.setChecked(True)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_6.addWidget(self.checkBox_29, 2, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_6.addWidget(self.checkBox_27, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_9)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 2, 1, 2)
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_28.setChecked(True)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_6.addWidget(self.checkBox_28, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_9)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 2, 5, 3, 1)
        self.line = QtWidgets.QFrame(self.tab_9)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 0, 1, 4, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_6.addWidget(self.pushButton_19, 0, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_9)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 0, 4, 4, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.gridLayout_19.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_26, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(PlateInspector)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.plateVis = PlateVisualizer(self.groupBox_3)
        self.plateVis.setObjectName("plateVis")
        self.gridLayout.addWidget(self.plateVis, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 2, 1, 1, 1)

        self.retranslateUi(PlateInspector)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlateInspector)

    def retranslateUi(self, PlateInspector):
        _translate = QtCore.QCoreApplication.translate
        PlateInspector.setWindowTitle(_translate("PlateInspector", "Form"))
        self.label_18.setText(_translate("PlateInspector", "Viewing Page 0 of 0"))
        self.plateViewer.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Plate views are displayed here. Each view (page) is a subsection of the entire screening plate.</p></body></html>"))
        self.groupBox_26.setTitle(_translate("PlateInspector", "Controls"))
        self.groupBox_29.setTitle(_translate("PlateInspector", "Page Navigation"))
        self.pushButton_17.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Navigate to previous page of images.</p><p>Shortcut: <span style=\" font-weight:600;\">Left Arrow Key</span></p></body></html>"))
        self.pushButton_17.setText(_translate("PlateInspector", "Previous"))
        self.pushButton_17.setShortcut(_translate("PlateInspector", "Left"))
        self.pushButton_21.setToolTip(_translate("PlateInspector", "<html><head/><body><p>If enabled, switch to the next date this sample was imaged.</p><p>Shortcut: <span style=\" font-weight:600;\">Ctrl+Right Arrow Key</span></p></body></html>"))
        self.pushButton_21.setText(_translate("PlateInspector", "Next Date"))
        self.pushButton_21.setShortcut(_translate("PlateInspector", "Ctrl+Right"))
        self.pushButton_22.setToolTip(_translate("PlateInspector", "<html><head/><body><p>If enabled, show this sample in a different imaging spectrum such as UV-TPEF or SHG.</p><p>Shortcut: <span style=\" font-weight:600;\">Ctrl+Up Arrow Key</span></p></body></html>"))
        self.pushButton_22.setText(_translate("PlateInspector", "Swap Spectrum"))
        self.pushButton_22.setShortcut(_translate("PlateInspector", "Ctrl+Up"))
        self.pushButton_20.setToolTip(_translate("PlateInspector", "<html><head/><body><p>If enabled, switch to the previous date this sample was imaged.</p><p>Shortcut: <span style=\" font-weight:600;\">Ctrl+Left Arrow Key</span></p></body></html>"))
        self.pushButton_20.setText(_translate("PlateInspector", "Previous Date"))
        self.pushButton_20.setShortcut(_translate("PlateInspector", "Ctrl+Left"))
        self.pushButton_18.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Navigate to the next page of images.</p><p>Shortcut: <span style=\" font-weight:600;\">Right Arrow Key</span></p></body></html>"))
        self.pushButton_18.setText(_translate("PlateInspector", "Next"))
        self.pushButton_18.setShortcut(_translate("PlateInspector", "Right"))
        self.spinBox.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Navigate directly to a specific page number.</p></body></html>"))
        self.label_3.setText(_translate("PlateInspector", "Show Page"))
        self.tab_7.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Highlight images based on either their MARCO or human classification. Images that meet your filter settings will be shown fully opaque while other images will be made translucent.</p></body></html>"))
        self.groupBox.setToolTip(_translate("PlateInspector", "Highlight images that meet your selected filters"))
        self.groupBox.setTitle(_translate("PlateInspector", "Classifier"))
        self.checkBox_21.setText(_translate("PlateInspector", "Human"))
        self.checkBox_22.setText(_translate("PlateInspector", "MARCO"))
        self.groupBox_2.setTitle(_translate("PlateInspector", "Image Type"))
        self.checkBox_25.setText(_translate("PlateInspector", "Precipitate"))
        self.checkBox_26.setText(_translate("PlateInspector", "Other"))
        self.checkBox_23.setText(_translate("PlateInspector", "Crystal"))
        self.checkBox_24.setText(_translate("PlateInspector", "Clear"))
        self.checkBox_6.setText(_translate("PlateInspector", "Favorite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("PlateInspector", "Image Filtering"))
        self.tab_8.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Color images in the view by either their human (your) classification or MARCO classification. Use the dropdown boxes to pick colors for each image classification.</p></body></html>"))
        self.label_22.setText(_translate("PlateInspector", "Color Intensity"))
        self.label_4.setText(_translate("PlateInspector", "TextLabel"))
        self.label_24.setText(_translate("PlateInspector", "Classifier"))
        self.label_19.setText(_translate("PlateInspector", "Crystal"))
        self.radioButton.setText(_translate("PlateInspector", "MARCO"))
        self.radioButton_2.setText(_translate("PlateInspector", "Human"))
        self.label_20.setText(_translate("PlateInspector", "TextLabel"))
        self.label_21.setText(_translate("PlateInspector", "Precipitate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("PlateInspector", "Image Coloring"))
        self.tab.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Select what information should be overlayed onto the images in the current view. Refresh the view for the current settings to be applied.</p></body></html>"))
        self.checkBox.setText(_translate("PlateInspector", "Date"))
        self.checkBox_4.setText(_translate("PlateInspector", "Human Classification"))
        self.checkBox_3.setText(_translate("PlateInspector", "Cocktail Number"))
        self.checkBox_5.setText(_translate("PlateInspector", "MARCO Classification"))
        self.label.setText(_translate("PlateInspector", "Include Checked Labels"))
        self.checkBox_2.setText(_translate("PlateInspector", "Well"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PlateInspector", "Labels"))
        self.pushButton_23.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Reload the current view. Similar to a refresh button. </p><p>Shortcut: <span style=\" font-weight:600;\">R</span></p></body></html>"))
        self.pushButton_23.setText(_translate("PlateInspector", "Reload Current View"))
        self.comboBox_7.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Select the number of images to be shown in each view.</p></body></html>"))
        self.checkBox_29.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Keep the aspect ratio of the images in the view. Favors accuracy to the original image over image size. Enabled by default.</p></body></html>"))
        self.checkBox_29.setText(_translate("PlateInspector", "Preserve Aspect Ratio"))
        self.checkBox_27.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Apply image filters selected in the <span style=\" font-style:italic;\">Image Filtering</span> tab.</p></body></html>"))
        self.checkBox_27.setText(_translate("PlateInspector", "Apply Image Filters"))
        self.label_23.setText(_translate("PlateInspector", "Images Per Plate"))
        self.checkBox_28.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Apply image colorings selected in the<span style=\" font-style:italic;\"> Image Coloring</span> tab</p></body></html>"))
        self.checkBox_28.setText(_translate("PlateInspector", "Apply Image Colors"))
        self.pushButton.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Save the current view to an image file. The more images in the current view the longer this will take and the larger the image file will be.</p></body></html>"))
        self.pushButton.setText(_translate("PlateInspector", "Save View"))
        self.pushButton_19.setToolTip(_translate("PlateInspector", "<html><head/><body><p>Apply the currently selected coloring and filtering options without having to reload the entire view. The <span style=\" font-style:italic;\">Apply Image Filters</span> check box must also be checked.</p><p>Shortcut: <span style=\" font-weight:600;\">A</span></p></body></html>"))
        self.pushButton_19.setText(_translate("PlateInspector", "Apply Plate Settings"))
        self.pushButton_19.setShortcut(_translate("PlateInspector", "A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("PlateInspector", "Plate View"))
        self.groupBox_3.setTitle(_translate("PlateInspector", "Plate Visualizer"))
        self.plateVis.setToolTip(_translate("PlateInspector", "Representation of what part of the screening plate you are currently viewing."))
from polo.widgets.plate_viewer import plateViewer
from polo.widgets.plate_visualizer import PlateVisualizer
